
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPARENT = 56;
  public static final int LPARENT = 55;
  public static final int LBRACKET = 59;
  public static final int CONST = 9;
  public static final int WITH = 26;
  public static final int PACKED = 15;
  public static final int GE = 38;
  public static final int DIVEXTENSION = 28;
  public static final int CASE = 25;
  public static final int SEMI = 48;
  public static final int FORWARD = 12;
  public static final int MINUS = 51;
  public static final int NOT = 4;
  public static final int AND = 2;
  public static final int LT = 35;
  public static final int RECORD = 29;
  public static final int TYPE = 10;
  public static final int NIL = 27;
  public static final int IN = 46;
  public static final int OR = 3;
  public static final int COMMA = 49;
  public static final int DOUBLEDOT = 58;
  public static final int DIV = 53;
  public static final int BEGIN = 13;
  public static final int NUM = 61;
  public static final int PLUS = 50;
  public static final int SCALEFACTOR = 45;
  public static final int EXIT = 18;
  public static final int SINGLEQUOTE = 40;
  public static final int ASSIGN = 33;
  public static final int IF = 19;
  public static final int WRITELN = 32;
  public static final int DOT = 57;
  public static final int LE = 36;
  public static final int OF = 16;
  public static final int EOF = 0;
  public static final int RBRACKET = 60;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int PROGRAM = 7;
  public static final int MOD = 54;
  public static final int CIRCUNFLEX = 42;
  public static final int EQ = 34;
  public static final int TIMES = 52;
  public static final int COLON = 47;
  public static final int EXTERNAL = 17;
  public static final int ELSE = 21;
  public static final int LETTER = 43;
  public static final int DOUBLEQUOTE = 41;
  public static final int TO = 24;
  public static final int FILE = 31;
  public static final int WHILE = 22;
  public static final int THEN = 20;
  public static final int NE = 39;
  public static final int END = 14;
  public static final int STRING = 63;
  public static final int STRINGCHARACTER = 44;
  public static final int FALSE = 6;
  public static final int LABEL = 8;
  public static final int GT = 37;
  public static final int VAR = 11;
  public static final int DO = 23;
  public static final int SET = 30;
  public static final int IDENTIFIER = 62;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "PROGRAM",
  "LABEL",
  "CONST",
  "TYPE",
  "VAR",
  "FORWARD",
  "BEGIN",
  "END",
  "PACKED",
  "OF",
  "EXTERNAL",
  "EXIT",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "TO",
  "CASE",
  "WITH",
  "NIL",
  "DIVEXTENSION",
  "RECORD",
  "SET",
  "FILE",
  "WRITELN",
  "ASSIGN",
  "EQ",
  "LT",
  "LE",
  "GT",
  "GE",
  "NE",
  "SINGLEQUOTE",
  "DOUBLEQUOTE",
  "CIRCUNFLEX",
  "LETTER",
  "STRINGCHARACTER",
  "SCALEFACTOR",
  "IN",
  "COLON",
  "SEMI",
  "COMMA",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "LPARENT",
  "RPARENT",
  "DOT",
  "DOUBLEDOT",
  "LBRACKET",
  "RBRACKET",
  "NUM",
  "IDENTIFIER",
  "STRING"
  };
}

