
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 78;
  public static final int IDENTIFIER = 14;
  public static final int PACKED = 27;
  public static final int TYPE = 50;
  public static final int CONST = 47;
  public static final int ASM = 15;
  public static final int BOOL_CONST = 2;
  public static final int UNTIL = 33;
  public static final int GEQ = 41;
  public static final int CONSTRUCTOR = 16;
  public static final int COMMA = 67;
  public static final int DOTS = 48;
  public static final int EQU = 40;
  public static final int INTEGER = 10;
  public static final int LPARENTHESIS = 71;
  public static final int SHR = 31;
  public static final int NOT = 38;
  public static final int NIL = 6;
  public static final int ARRAY = 7;
  public static final int OBJECT = 11;
  public static final int SHL = 30;
  public static final int VAR = 46;
  public static final int INLINE = 24;
  public static final int THEN = 54;
  public static final int GOTO = 21;
  public static final int RECORD = 12;
  public static final int MOD = 81;
  public static final int PTR = 82;
  public static final int NUMBER = 83;
  public static final int STRING_CHAR = 5;
  public static final int PLUS = 76;
  public static final int UNIT = 32;
  public static final int WHILE = 59;
  public static final int IMPLEMENTATION = 22;
  public static final int ASSIGN = 64;
  public static final int INTERFACE = 25;
  public static final int CHAR = 9;
  public static final int BOOLEAN = 8;
  public static final int DO = 58;
  public static final int FOR = 56;
  public static final int DIV = 79;
  public static final int DOWNTO = 18;
  public static final int DIGIT = 75;
  public static final int INT_CONST = 4;
  public static final int ELSE = 55;
  public static final int DOT = 68;
  public static final int LTH = 44;
  public static final int PROCEDURE = 62;
  public static final int EOF = 0;
  public static final int SEMICOLON = 66;
  public static final int FOWARD = 20;
  public static final int FUNCTION = 61;
  public static final int REPEAT = 28;
  public static final int LABEL = 26;
  public static final int MINUS = 77;
  public static final int SINGLEQUOTE = 73;
  public static final int RPARENTHESIS = 72;
  public static final int DESTRUCTOR = 17;
  public static final int IN = 23;
  public static final int OR = 37;
  public static final int SET = 29;
  public static final int error = 1;
  public static final int CHAR_CONST = 3;
  public static final int GTH = 42;
  public static final int DIVINT = 80;
  public static final int IF = 53;
  public static final int OF = 49;
  public static final int END = 52;
  public static final int COLON = 65;
  public static final int FILE = 19;
  public static final int RBRACKET = 70;
  public static final int BEGIN = 51;
  public static final int CASE = 60;
  public static final int STRING = 13;
  public static final int NEQ = 45;
  public static final int PROGRAM = 63;
  public static final int DOUBLEQUOTE = 74;
  public static final int AND = 36;
  public static final int UMINUS = 84;
  public static final int TO = 57;
  public static final int LBRACKET = 69;
  public static final int WITH = 35;
  public static final int USES = 34;
  public static final int XOR = 39;
  public static final int LEQ = 43;
  public static final int SCALEFACTOR = 85;
  public static final int TRUE = 86;
  public static final int FALSE = 87;
  public static final int LETTER = 88;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL_CONST",
  "CHAR_CONST",
  "INT_CONST",
  "STRING_CHAR",
  "NIL",
  "ARRAY",
  "BOOLEAN",
  "CHAR",
  "INTEGER",
  "OBJECT",
  "RECORD",
  "STRING",
  "IDENTIFIER",
  "ASM",
  "CONSTRUCTOR",
  "DESTRUCTOR",
  "DOWNTO",
  "FILE",
  "FOWARD",
  "GOTO",
  "IMPLEMENTATION",
  "IN",
  "INLINE",
  "INTERFACE",
  "LABEL",
  "PACKED",
  "REPEAT",
  "SET",
  "SHL",
  "SHR",
  "UNIT",
  "UNTIL",
  "USES",
  "WITH",
  "AND",
  "OR",
  "NOT",
  "XOR",
  "EQU",
  "GEQ",
  "GTH",
  "LEQ",
  "LTH",
  "NEQ",
  "VAR",
  "CONST",
  "DOTS",
  "OF",
  "TYPE",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "FOR",
  "TO",
  "DO",
  "WHILE",
  "CASE",
  "FUNCTION",
  "PROCEDURE",
  "PROGRAM",
  "ASSIGN",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "LBRACKET",
  "RBRACKET",
  "LPARENTHESIS",
  "RPARENTHESIS",
  "SINGLEQUOTE",
  "DOUBLEQUOTE",
  "DIGIT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "DIVINT",
  "MOD",
  "PTR",
  "NUMBER",
  "UMINUS",
  "LETTER",
  "TRUE",
  "FASE",
  "SCALEFACTOR"
  };
}

