
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package artefatos;

/** CUP generated interface containing symbol constants. */
public interface sym {
	  /* terminals */
	  public static final int MINUS = 4;
	  public static final int UMINUS = 5;
	  public static final int NUMBER = 9;
	  public static final int SEMICOLON = 2;
	  public static final int EOF = 0;
	  public static final int PLUS = 3;
	  public static final int error = 1;
	  public static final int RPARENT = 8;
	  public static final int TIMES = 6;
	  public static final int LPARENT = 7;
	  public static final String[] terminalNames = new String[] {
	  "EOF",
	  "error",
	  "SEMICOLON",
	  "PLUS",
	  "MINUS",
	  "UMINUS",
	  "TIMES",
	  "LPARENT",
	  "RPARENT",
	  "NUMBER"
	  };
	  
}

